// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWebAPI.Models;
using UserWebAPI.Entities;

namespace UserWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190910010714_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ClaimType");

                b.Property<string>("ClaimValue");

                b.Property<int>("UserId");

                b.HasKey("Id");

                b.ToTable("UserClaim");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("ProviderKey");

                b.Property<string>("LoginProvider");

                b.Property<string>("ProviderDisplayName");

                b.Property<int>("UserId");

                b.HasKey("ProviderKey", "LoginProvider");

                b.ToTable("UserLogin");
            });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<int>("RoleId");

                b.Property<int>("UserId");

                b.HasKey("RoleId", "UserId");

                b.ToTable("UserRole");
            });

            modelBuilder.Entity<User>(b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Email");

                b.Property<string>("FirstName");

                b.Property<string>("LastName");

                b.Property<string>("PasswordHash");

                b.Property<string>("UserName");

                b.HasKey("Id");

                b.ToTable("User");
            });

            modelBuilder.Entity<Role>(c =>
            {
                c.Property(r => r.Id).ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
                c.HasKey("Id");

                c.ToTable("Role");
            });
#pragma warning restore 612, 618
        }
    }
}
